# Copyright 2021 Jeff Hillman
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  hostname:
    default: ""
    description: >
      The external hostname this application should be available on. If unset,
      it will default to the deployed application name in the model.
    type: string
  file-server:
    default: False
    description: >
      Enable file server functionality
    type: boolean
  browseable:
    default: False
    description: >
      Allows file listings for requests to directories that do not have an index file. 
      NOTE This should only be enable if file-server is set to True.
    type: boolean
